id: P004129
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:55:04.661919
source_metadata:
  id: bdr:W00EGS1018126
  title: འཇུ་མི་ཕམ་གྱི་སྨན་ཡིག་གཅེས་བསྡུས
  author: ''
  volumes:
    8a47f74a363646b180f5f9748b2f10f9:
      image_group_id: I1PD421
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
