id: I2D32188A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:03:05+00:00'
last_modified: '2022-06-07T20:27:04.840649+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1018126
  title: འཇུ་མི་ཕམ་གྱི་སྨན་ཡིག་གཅེས་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2B32:
      image_group_id: I1PD421
      title: ''
      total_pages: 502
      order: 1
      base_file: 2B32.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
